#!/usr/bin/env bash
# Transfer a file to your server

if [ "$#" -eq 4 ]; then
  scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~

else
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1

fi
