#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

# Checks for $1 argument(argv)
if [ "$1" ]
then
# ping: test the reachability of a host on a network and measure the round-trip time (RTT) for packets to travel to the destination and back.
# ping: Used to send five ICMP echo request packets (pings) to specified IP address
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"

# fi: Indciates the end of if statement
fi
