#!/usr/bin/env bash
#Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

# trap: Indicates the process is already in the process state and should be stopped and killed
# SIGTERM: Request the termination of a process
trap 'echo "I am invincible!!!"' SIGTERM

while true
do 
	echo "To infinity and beyond"
	# sleep: Indicates the seconds to delay the process until it's completed successfully
	sleep 2
	
done
