#!/usr/bin/env bash
# Bash script that indefinitely writes "I am alive" to the file "/tmp/my_process".

while display=0;
do
  echo "I am alive!" >> /tmp/my_process
  ((display++))
  # sleep: Indicates the seconds to delay the process until it's completed successfully
  sleep 2
done
