#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop
script="Best School"
bash=0

# lt: Indicates that the script being executed is less than 10
while [ $bash -lt 10 ];
do
    echo "$script"
    ((bash++))
done
