#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
script="Best School"
(( bash = 0 ))

#lt: Indciates the script being executed is less than or == 10
while [ $bash -lt 10 ];
do
echo "$script"
(( bash++ ))
done
