#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using until loop
script="Best School"
(( bash = 0 ))

#gt: executes a block of code until the specified condition becomes true
until [ $bash -gt 9 ];
do
echo "$script"
(( bash++ ))
done
