#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using until loop
script="Best School"
(( bash = 0 ))

#lt: Indciates the script being executed is less than or == 10
until [ $bash -gt 9 ];
do
echo "$script"
(( bash++ ))
done
