#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20
bash=1

while [ "$bash" -le 20 ];
do
    echo "$bash"

    case "$bash" in
        # displays 4 and then bad luck from China for the 4th loop iteration
        4)
            echo "bad luck from China"
            ;;
        # displays 9 and then bad luck from Japan for the 9th loop iteration
        9)
            echo "bad luck from Japan"
            ;;
        # displays 17 and then bad luck from Italy for the 17th loop iteration
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo -n
            ;;
	# esc: Indicates the end of a case statement
    esac

    ((bash++))
done
