#!/usr/bin/env bash
# This script that gives information about the 'school' file
bash="school"

# Check if the file exists
if [ -e "$bash" ]
then
	echo "school file exists"

	# Check if the file is not empty
	if [ -s "$bash" ]
	then
		echo "school file is not empty"

	# Check if the file is empty
	else
		echo "school file is empty"
	fi

	# Check if the file is a regular file
	if [ -f "$bash" ]
	then
		echo "school is a regular file"
	fi

# Check if the file does not exist
else
	echo "school file does not exist"
# fi: Indciates the end of if statement
fi
