#!/usr/bin/env bash
# Script with 7 lines or less

pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
`sh@Cher_BaTkyH^22.
@sZczeb_RzesZyn~23.